### ISSUE TITLE
#1 404 NOT FOUND ERROR

### ISSUE THREAD

**Issue by sanghanam** [uhh-lt/wsd#1]
Hello

When I enter this command "wget http://ltdata1.informatik.uni-hamburg.de/joint/wsd/20170721_wsd_images.tgz", the 404 not found error message is printed.

I think that you distributed a learned model and DB as a docker image.

How can I use it?

**Comment by alexanderpanchenko** [comment]
Now readme is updated: you have new paths to both image and db dumps, which should work. Note that the db dump is updated. 

Let us know if you have problems during the installation.
