### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kirillkh** [uhh-lt/wsd#3]
Hi!

What is the license for this project?

**Comment by alexanderpanchenko** [comment]
we are currently using Stanford CoreNLP for NER, therefore our license is
the same as theirs, ie GPL. it is however relatively easy to use another
out of the box NER tagger e.g. Scala NLP with a better licence if it is
really needed

**Comment by fmarten** [comment]
There is an somewhat outdated branch avoiding Stanford CoreNLP and GPL. It might be a good starting point if this is needed.

https://github.com/uhh-lt/wsd/tree/migrate-to-scalanlp

Closing this issue as it has been inactive for some time.
