### ISSUE TITLE
wsp_default database does not exist

### ISSUE THREAD

**Issue by ylitripnester** [uhh-lt/wsd#4]
Hi, 
When I try this docker, I always has this problem of : wsp_default database does not exist
thanks for help

My computer is Ubuntu

**Comment by alexanderpanchenko** [comment]
Hello,

Can you please provide more context?

**Comment by dengke-li** [comment]
Hello,
I meet the same problem when I follow the two command ./wsd model:donwload, and ./wsd web-app:start for the project https://github.com/uhh-lt/wsd, I check the log when I do a request and find there is following error:
play.api.UnexpectedException: Unexpected exception[PSQLException: FATAL: database "wsp_default" does not exist]

**Comment by fmarten** [comment]
Hi ylitripnester,
most likely the download of the DB image did not succeed.

There is another issue #6 discussing this problem. Lets continue any further discussion there.

Closing this issue as duplicate.
