### ISSUE TITLE
how to add inventory into mysql

### ISSUE THREAD

**Issue by dengke-li** [uhh-lt/wsd#5]
Hello,

I am trying to install the WSD-server (https://github.com/eugenso/WSD-Server)
in one step is 'Add the inventories to a MySQL database', but when I download the 3 inventories, how can I add the three inventories into mysql? It seems that the content of  inventories is not regular.

urgent for your help

**Comment by fmarten** [comment]
Hi linuslukia,

it sound to me that this issue is related to the repository which you posted above: https://github.com/eugenso/WSD-Server

Can you explain how this relates to this https://github.com/uhh-lt/wsd repository?

**Comment by dengke-li** [comment]
hello,
i try to install wsd, and not sucess because of the lack of wsd_default
database, so then i find wsd_server project of the same university, and i
think this is the version standalone, so i try to install it on my
computer, i follow the steps on the readme, then download model and three
data file in order to add it inysql, but the data in the files seems not
regular, so i want to ask how to add it in mysql?

best wishes

2018年1月28日 下午4:44，"Fide Marten" <notifications@github.com>写道：

**Comment by fmarten** [comment]
I understand, but the https://github.com/eugenso/WSD-Server is a separate project.
I will hence close this issue.

With the database issue in #6, I can however help you.
